### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ghost** [lcxfs1991/koa-socket.io#1]
function *respond(next) {
         ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/lily/Documents/Resource/Examples/koa-socket.io/index.js:1:73)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by lcxfs1991** [comment]
你可以升级node到4.0版本。好像node4.0以下，需要用harmony参数才能支持generator.
